### ISSUE TITLE
Label format

### ISSUE THREAD

**Issue by Kshitizbansal** [valeoai/RADIal#5]
Hi authors,

How do we obtain the dimensions of the box labels given in the CSV file? It seems to contain only a 3D point for Lidar and 2D point for Radar. In the corresponding paper https://arxiv.org/pdf/2112.10646v1.pdf, 2D boxes with dimensions are used. Is there a plan to release the dimension information as well?

Thank you

**Comment by jrebut** [comment]
Hi Kshitizbansal,

we are sorry if there are some confusions. As you noticed, labels are described by a 2D point for the radar. Object width/height are not provided in the current version. It should be pretty simple from the laser data to estimate object width. However, because the laser scanner has only 16 layers, you should then consider the image to estimate the object height: you have the size of the boudning box in pixels, and width in meter.
We will consider your request in the near future

Regards
Julien
