### ISSUE TITLE
The raw data on Google Drive is not available now

### ISSUE THREAD

**Issue by EricLiuhhh** [valeoai/RADIal#63]
Thank you for your excellent work! When I went to download the raw data, Google Drive said I didn't have permission. Is the original data not public now, or is there something wrong with Google Drive. Sincerely, Thank you!

**Comment by ArthurOuaknine** [comment]
Due to the some issues we encounter with the storage, the data is temporarily unavailable. We are currently working on a new solution to make the dataset available again as soon as possible. Thank you for your patience and understanding. We apologize for the inconvenience.
Refer to issue #62 for follow up

**Comment by coding-and-coding** [comment]
> Due to the some issues we encounter with the storage, the data is temporarily unavailable. We are currently working on a new solution to make the dataset available again as soon as possible. Thank you for your patience and understanding. We apologize for the inconvenience. Refer to issue #62 for follow up

hello, the raw data is not available in google drive now, can you share it with me via some ways? thanks!
