### ISSUE TITLE
Request for more information on radar used

### ISSUE THREAD

**Issue by Kshitizbansal** [valeoai/RADIal#7]
Hi authors,
```
RangeBin_candidates = [[i] for i in RangeBin]
doppler_indexes = []
for doppler_bin in DopplerBin_candidates:
    DopplerBinSeq = np.remainder(doppler_bin+ self.dividend_constant_arr, self.numChirps)
    DopplerBinSeq = np.concatenate([[DopplerBinSeq[0]],DopplerBinSeq[5:]]).astype('int')
    doppler_indexes.append(DopplerBinSeq)
    
MIMO_Spectrum = RD_spectrums[RangeBin_candidates,doppler_indexes,:].reshape(len(DopplerBin_candidates),-1)
```

This is a code snippet from __get_PCL function. `MIMO_Spectrum` (512x256x12x16) is a resampled form of `RD_spectrums` (512x256x16). Could you please help me understand the logic behind this resampling to form the `MIMO_Spectrum`? Also, would it be possible to release some more information about the used radar? For example, a datasheet that mentions the Tx/Rx arrangement and chirp configurations. Thanks in advance.

**Comment by jrebut** [comment]
Hi, unfortunately, we can not release the datasheet of the used Radar, this is a prototype.
However, we can help to understand how it works. I would first recommend to read our paper https://arxiv.org/pdf/2112.10646.pdf, the section MIMO pre-ecnoder will help to understand how it works.

This Radar has 16 Rx and 12 Tx. Therefore, we have 16 RD spectrums of shape (512x256x16), one for each Rx antenna. This Radar uses a MIMO configuration, that is to say, all the emitters emit at the same time and all the receivers receive at the same time. This lead to see more than one peak per real target in the RD spectrums. To be accurate, we have as many peaks as Tx.

So, in this MIMO configuration with a target object at the Range R, the RD spectrums will contain 12 peaks located at row R, with different Doppler values. Each peak is actually a transmitter signal received by the 16 Rx antennas. Therefore, the full MIMO signal is 12 received signal times 16 receivers --> 192 complex values. 

Because it is not convenient to get these values (signal interleaved), we resample the input RD spectrums which have interleaved signals to a MIMO spectrum on size (512x256x192). In this new tensor, each RD point has its MIMO values on the channel axis.

I hope it will help
Julien
