### ISSUE TITLE
Broken raw data links

### ISSUE THREAD

**Issue by jonasdaugalas** [valeoai/RADIal#8]
Thanks a lot for the dataset. Great work!

I am unable to download the raw data via the provided links in the `download_urls.txt` file. 

```
$ wget -c -i download_urls.txt -P /my/target/path
--2022-01-20 09:25:43--  https://www.dropbox.com/s/9tcmxfo8z9edawq/RECORD2020-11-21_11.54.31.zip
Resolving www.dropbox.com (www.dropbox.com)... 2620:100:6022:18::a27d:4212, 162.125.66.18
Connecting to www.dropbox.com (www.dropbox.com)|2620:100:6022:18::a27d:4212|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/raw/9tcmxfo8z9edawq/RECORD2020-11-21_11.54.31.zip [following]
--2022-01-20 09:25:44--  https://www.dropbox.com/s/raw/9tcmxfo8z9edawq/RECORD2020-11-21_11.54.31.zip
Reusing existing connection to [www.dropbox.com]:443.
HTTP request sent, awaiting response... 404 Not Found
2022-01-20 09:25:44 ERROR 404: Not Found.

...
```

**Comment by jrebut** [comment]
Hi,

Indeed, we received a warning yesterday from DropBox due to high a number of downloads. Sadly, they decided to deactivate the link without notification! A part of the dataset is no more available.  We will check how to avoid that again and will do our best to reactivate the links quickly. Please, check on a regular basis

Best,
Julien
